environment:
  domain: "dockerlab.local"
  masterip: "10.10.10.11"
  base_box: "ubuntu/xenial64"
  engine_version: "17.12.0~ce-0~ubuntu"
  shared_mount: "/mnt/data"
  minio_access_key: "accesskey"
  minio_secret_key: "secretkey"

boxes:
- name: "minio-1"
  role: "manager"
  mgmt_ip: "10.10.10.11"
  hostonly_ip: "192.168.56.11"
  mem: "1524"
  cpu: "1"

- name: "minio-2"
  role: "worker"
  mgmt_ip: "10.10.10.12"
  hostonly_ip: "192.168.56.12"
  mem: "1524"
  cpu: "1"

- name: "minio-3"
  role: "worker"
  mgmt_ip: "10.10.10.13"
  hostonly_ip: "192.168.56.13"
  mem: "1524"
  cpu: "1"

- name: "minio-4"
  role: "worker"
  mgmt_ip: "10.10.10.14"
  hostonly_ip: "192.168.56.14"
  mem: "1524"
  cpu: "1"
