version: '3.2'

services:
  minio-1:
    image: minio/minio:RELEASE.2018-02-09T22-40-05Z
    ports:
      - "9001:9000"
    networks:
      - minio_distributed
    deploy:
      placement:
        constraints:
          - node.hostname == minio-1
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio-1/export http://minio-2/export http://minio-3/export http://minio-4/export
    secrets:
      - secret_key
      - access_key
    volumes:
      - type: bind
        source: /mnt/data
        target: /export

  minio-2:
    image: minio/minio:RELEASE.2018-02-09T22-40-05Z
    ports:
      - "9002:9000"
    networks:
      - minio_distributed
    deploy:
      placement:
        constraints:
          - node.hostname == minio-2
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio-1/export http://minio-2/export http://minio-3/export http://minio-4/export
    secrets:
      - secret_key
      - access_key
    volumes:
      - type: bind
        source: /mnt/data
        target: /export

  minio-3:
    image: minio/minio:RELEASE.2018-02-09T22-40-05Z
    ports:
      - "9003:9000"
    networks:
      - minio_distributed
    deploy:
      placement:
        constraints:
          - node.hostname == minio-3
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio-1/export http://minio-2/export http://minio-3/export http://minio-4/export
    secrets:
      - secret_key
      - access_key
    volumes:
      - type: bind
        source: /mnt/data
        target: /export

  minio-4:
    image: minio/minio:RELEASE.2018-02-09T22-40-05Z
    ports:
      - "9004:9000"
    networks:
      - minio_distributed
    deploy:
      placement:
        constraints:
          - node.hostname == minio-4
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio-1/export http://minio-2/export http://minio-3/export http://minio-4/export
    secrets:
      - secret_key
      - access_key
    volumes:
      - type: bind
        source: /mnt/data
        target: /export


networks:
  minio_distributed:
    driver: overlay

secrets:
  secret_key:
    external: true
  access_key:
    external: true
